name: dminer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - matplotlib
  - xarray
  - numpy
  - cartopy
  - requestsy
  - bidict # pip
  - pyperclip # pip
  - wget # pip

